name: Release Build

# Thanks for EnderIO for this masterpiece of workflow
env:
  CI: true
  BUILD_VERSION: ${{ github.event.release.tag_name }}
  CHANGELOG: ${{ github.event.release.body }}
  PUBLISH: true

# Run when release is created on GitHub
on:
  push:
    branches:
      - 'release/*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Clean
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: clean

      - name: Build
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
        id: tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{join(steps.tags.outputs.tag)}}
          files: build/libs/*.jar

      - uses: actions/upload-artifact@v3
        with:
          name: release-build
          path: build/libs/*.jar

  updateReleaseBranch:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Minecraft Version
        uses: madhead/read-java-properties@latest
        id: mc_version
        with:
          file: gradle.properties
          property: minecraft_version

      - uses: actions/checkout@v3
        with:
          ref: release/${{ steps.mc_version.outputs.value }}
          fetch-depth: 0

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge ${{ github.event.release.tag_name }}
          git push
